# Sources based on https://docs.blender.org/api/blender2.8/bpy.types.RenderEngine.html
# blender -P blender_render_engine.trace.py  -p 900 1000 3000 1500 
import bpy
import bgl
import time
import numpy

t0 = time.time()

def log(s):
    t = '%.6f' % (time.time() - t0)
    print('%s | %s' % (t, s))
    

class CustomRenderEngine(bpy.types.RenderEngine):
    # These three members are used by blender to set up the
    # RenderEngine; define its internal name, visible name and capabilities.
    bl_idname = "DOT"
    bl_label = "Dot"
    bl_use_preview = False
    bl_use_eevee_viewport = False
    bl_use_shading_nodes_custom = False     # Default: True

    # Init is called whenever a new render engine instance is created. Multiple
    # instances may exist at the same time, for example for a viewport and final
    # render.
    def __init__(self):
        
        self.scene_data = None
        self.draw_data = None
        
        self.render_count = 0
        self.draw_count = 0
        self.update_count = 0
        self.dimensions = None

    # This is the method called by Blender for both final renders (F12) and
    # small preview for materials, world and lights.
    def render(self, depsgraph):
        
        self.render_count += 1
        
        print('-' * 40)
        log('render #%d' % self.render_count)
        print('-' * 40)
        
        num_objects = 0
        num_instances = 0
        count_by_type = {}
        count_by_instanced_object = {}
        
        def P(obj):
            return '%s (0x%x)' % (obj, id(obj))
            
        nodes = {}
        edges = {}
        
        #depsgraph.debug_relations_graphviz('relations.dot')
        
        nodes['depsgraph__object_instances'] = dict(name='depsgraph.object_instances')
                
        for idx, instance in enumerate(depsgraph.object_instances):
            
            obj = instance.object
            objid = 'instance__%d' % idx
            print(objid, instance.matrix_world)
            
            assert objid not in nodes
            
            nodes[objid] = dict(id=objid, type=obj.type, name=obj.name)
            edges[('depsgraph__object_instances',objid)] = dict(label='[%d]' % idx)
            
            edges[(objid, obj.original.as_pointer())] = dict(label='obj.original', color='orange')
            
            if instance.is_instance:
                nodes[objid]['is_instance'] = True
                nodes[objid]['random_id'] = instance.random_id
                
                edges[(objid, instance.instance_object.as_pointer())] = dict(label='instance.instance_object', color='"#008000"')
                
                # Object was generated by another object
                # instance.instance_object = evaluated object which is being instanced by this iterator
                print('DEPSGRAPH INSTANCE object %s, type=%s (instanced), random_id=%d, instance_object=%s' % \
                    (P(obj), obj.type, instance.random_id, P(instance.instance_object)))
                #assert id(obj.original) == id(instance.instance_object)
            else:
                print('DEPSGRAPH INSTANCE object %s, type=%s (not instanced)' % (P(obj), obj.type))
            
            # Evaluated object the iterator points to
            print('instance.object %s, instance.object.original %s' % (P(obj), P(obj.original)))
            
            if instance.parent is not None:
                # If the object is an instance, the parent object that generated it.
                # This is even set when a particle system generated the object, but no parenting relation was active
                print('instance.parent = %s' % P(instance.parent))
                
                edges[(objid, instance.parent.as_pointer())] = dict(label='instance.parent', color='purple')
                
            if instance.particle_system is not None:
                # Evaluated particle system that this object was instanced from
                print('instance.particle_system = %s' % P(instance.particle_system))
                
                edges[(objid, instance.particle_system.as_pointer())] = dict(label='instance.particle_system')
            
            # Actual data-block from .blend file (Main database) that generated that evaluated one
            assert obj.original == depsgraph.scene.objects[obj.name]
            
            type = obj.type
            if obj.type not in count_by_type:
                count_by_type[type] = 1
            else:
                count_by_type[type] += 1
            
            num_objects += 1
            if instance.is_instance:
                num_instances += 1
                instanced_object_name = instance.instance_object.name
                if instanced_object_name not in count_by_instanced_object:
                    count_by_instanced_object[instanced_object_name] = 1
                else:
                    count_by_instanced_object[instanced_object_name] += 1
                    
            if type == 'MESH':
                mesh = obj.data
                print('[%s] MESH %d vertices, %s polygons' % (obj.name, len(mesh.vertices), len(mesh.polygons)))
                original_object = instance.instance_object
                original_mesh = instance
                print
                
        nodes['depsgraph__ids'] = dict(name='depsgraph.ids')
        for idx, idobj in enumerate(depsgraph.ids):
            nodes[idobj.as_pointer()] = dict(name=idobj.name)
            edges[('depsgraph__ids', idobj.as_pointer())] = dict(label='[%d]' % idx)
                
        nodes['depsgraph__objects'] = dict(name='depsgraph.objects')
        for idx, obj in enumerate(depsgraph.objects):
            nodes[obj.as_pointer()] = dict(name=obj.name)
            edges[('depsgraph__objects', obj.as_pointer())] = dict(label='[%d]' % idx)
            
        nodes['scene__objects'] = dict(name='depsgraph.scene.objects')
        for idx, obj in enumerate(depsgraph.scene.objects):
            nodes[obj.as_pointer()] = dict(name=obj.name)
            edges[('scene__objects', obj.as_pointer())] = dict(label='[%d]' % idx)
                
        # Write dot file
        
        with open('depsgraph.dot', 'wt') as f:
            
            f.write('digraph {\n')
            f.write('rankdir=LR;\n')
            
            for nodeid, values in nodes.items():
                label = values['name']+'\\n' if 'name' in values else ''
                for k in sorted(values.keys()):
                    if k == 'name':
                        continue
                    label += "\\n%s='%s'" % (k, values[k])
                f.write('%s [label="%s"];\n' % (nodeid, label))
                
            for edge, values in edges.items():
                if 'label' in values:
                    label = 'label="%s"' % values['label']
                color = values['color'] if 'color' in values else 'black'
                f.write('%s -> %s [color=%s;fontcolor=%s;%s];\n' % (edge[0], edge[1], color, color, label))
            
            f.write('}\n')
        
        
        # Show something
                
        scene = depsgraph.scene
        scale = scene.render.resolution_percentage / 100.0
        self.size_x = int(scene.render.resolution_x * scale)
        self.size_y = int(scene.render.resolution_y * scale)

        color = [0.2, 0.1, 0.1, 1.0]
        pixel_count = self.size_x * self.size_y
        rect = [color] * pixel_count
        result = self.begin_result(0, 0, self.size_x, self.size_y)
        layer = result.layers[0].passes["Combined"]
        layer.rect = rect
        self.end_result(result)
                
        print()
        print('%d object instances in depsgraph' % num_objects)
        print('%d are instances' % num_instances)
        print('%d objects were instanced' % len(count_by_instanced_object))
        print()
        print('Count by type:')
        for k in sorted(count_by_type.keys()):
            print('%8d | %-14s ' % (count_by_type[k], k))
        print()
        print('Count by instanced object:')
        for n in sorted(count_by_instanced_object):
            print('%8d | %-32s ' % (count_by_instanced_object[n], n))
        print()            

    # For viewport renders, this method gets called once at the start and
    # whenever the scene or 3D viewport changes. This method is where data
    # should be read from Blender in the same thread. Typically a render
    # thread will be started to do the work while keeping Blender responsive.
    def view_update(self, context, depsgraph):
        
        self.update_count += 1
        
        print('-' * 40)
        log('view_update #%d' % self.update_count)
        print('-' * 40)
        
        region = context.region
        view3d = context.space_data
        scene = depsgraph.scene
        
        # Get viewport dimensions
        dimensions = region.width, region.height
                
        types = ['ACTION', 'ARMATURE', 'BRUSH', 'CAMERA', 'CACHEFILE', 'CURVE', 'FONT', 'GREASEPENCIL', 'COLLECTION', 'IMAGE', 'KEY', 'LIGHT', 'LIBRARY', 'LINESTYLE', 'LATTICE', 'MASK', 'MATERIAL', 'META', 'MESH', 'MOVIECLIP', 'NODETREE', 'OBJECT', 'PAINTCURVE', 'PALETTE', 'PARTICLE', 'LIGHT_PROBE', 'SCENE', 'SOUND', 'SPEAKER', 'TEXT', 'TEXTURE', 'WINDOWMANAGER', 'WORLD', 'WORKSPACE']
        for t in types:
            if depsgraph.id_type_updated(t):
                print("Type %s updated" % t)

        print()
        
        for update in depsgraph.updates:
            print('Datablock "%s" updated (%s)' % (update.id.name, type(update.id)))
            if update.is_updated_geometry:
                print('-- geometry was updated')
            if update.is_updated_transform:
                print('-- transform was updated')
                
        print()

    # For viewport renders, this method is called whenever Blender redraws
    # the 3D viewport. The renderer is expected to quickly draw the render
    # with OpenGL, and not perform other expensive work.
    # Blender will draw overlays for selection and editing on top of the
    # rendered image automatically.
    def view_draw(self, context, depsgraph):
        
        # See https://github.com/LuxCoreRender/BlendLuxCore/blob/master/draw/viewport.py

        self.draw_count += 1
        
        print('-' * 40)
        log('view_draw #%d' % self.draw_count)
        print('-' * 40)
        
        region = context.region
        assert region.type == 'WINDOW'        
        assert context.space_data.type == 'VIEW_3D'
        
        region_data = context.region_data
        space_data = context.space_data
        
        # view clipping has no effect on these matrices
        print('WINDOW', region_data.window_matrix)
        print('PERSPECTIVE', region_data.perspective_matrix)    # = window * view
        print('VIEW', region_data.view_matrix)
        
        print('view location', region_data.view_location)
        print('view rotation', region_data.view_rotation)       # Quat
        print('perspective %d' % (region_data.is_perspective))
        
        # view3d.perspective_matrix = window_matrix * view_matrix
        perspective_matrix = region_data.perspective_matrix
        
        print('space_data.lens', space_data.lens)   # Always set to viewport lens setting, even when in camera view
        
        #print('region_data', dir(region_data))
        print('region_data.view_perspective', region_data.view_perspective) # PERS, ORTHO or CAMERA
        
        #print('space_data', dir(space_data))
        print('space_data.camera', space_data.camera)
        #print('space_data.use_local_camera', space_data.use_local_camera)  # No relation to camera view yes/no
        
        scene = depsgraph.scene

        # Get viewport dimensions
        dimensions = region.width, region.height
        
        if dimensions != self.dimensions:
            print('Dimensions changed to %d x %d' % dimensions)
            self.dimensions = dimensions        
            
        print('aspect (dims) %.3f' % (self.dimensions[0]/self.dimensions[1]))
        print('aspect (window matrix) %.3f' % (region_data.window_matrix[1][1] / region_data.window_matrix[0][0]))
        
        # Bind shader that converts from scene linear to display space,
        bgl.glEnable(bgl.GL_BLEND)
        bgl.glBlendFunc(bgl.GL_ONE, bgl.GL_ONE_MINUS_SRC_ALPHA);
        self.bind_display_space_shader(scene)

        if not self.draw_data or self.draw_data.dimensions != dimensions:
            self.draw_data = CustomDrawData(dimensions)

        self.draw_data.draw()

        self.unbind_display_space_shader()
        bgl.glDisable(bgl.GL_BLEND)
        
        print()
        


class CustomDrawData:
    def __init__(self, dimensions):
        log('CustomDrawData.__init__()')
        
        # Generate dummy float image buffer
        self.dimensions = dimensions
        width, height = dimensions
        
        pixels = numpy.full(width*height*4, 0.3, dtype=numpy.float32)
        #pixels = [0.1, 0.2, 0.1, 1.0] * width * height
        pixels = bgl.Buffer(bgl.GL_FLOAT, width * height * 4, pixels)

        # Generate texture
        self.texture = bgl.Buffer(bgl.GL_INT, 1)
        bgl.glGenTextures(1, self.texture)
        bgl.glActiveTexture(bgl.GL_TEXTURE0)
        bgl.glBindTexture(bgl.GL_TEXTURE_2D, self.texture[0])
        bgl.glTexImage2D(bgl.GL_TEXTURE_2D, 0, bgl.GL_RGBA16F, width, height, 0, bgl.GL_RGBA, bgl.GL_FLOAT, pixels)
        bgl.glTexParameteri(bgl.GL_TEXTURE_2D, bgl.GL_TEXTURE_MIN_FILTER, bgl.GL_LINEAR)
        bgl.glTexParameteri(bgl.GL_TEXTURE_2D, bgl.GL_TEXTURE_MAG_FILTER, bgl.GL_LINEAR)
        bgl.glBindTexture(bgl.GL_TEXTURE_2D, 0)

        # Bind shader that converts from scene linear to display space,
        # use the scene's color management settings.
        shader_program = bgl.Buffer(bgl.GL_INT, 1)
        bgl.glGetIntegerv(bgl.GL_CURRENT_PROGRAM, shader_program);

        # Generate vertex array
        self.vertex_array = bgl.Buffer(bgl.GL_INT, 1)
        bgl.glGenVertexArrays(1, self.vertex_array)
        bgl.glBindVertexArray(self.vertex_array[0])

        texturecoord_location = bgl.glGetAttribLocation(shader_program[0], "texCoord");
        position_location = bgl.glGetAttribLocation(shader_program[0], "pos");

        bgl.glEnableVertexAttribArray(texturecoord_location);
        bgl.glEnableVertexAttribArray(position_location);

        # Generate geometry buffers for drawing textured quad
        position = [0.0, 0.0, width, 0.0, width, height, 0.0, height]
        position = bgl.Buffer(bgl.GL_FLOAT, len(position), position)
        texcoord = [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0]
        texcoord = bgl.Buffer(bgl.GL_FLOAT, len(texcoord), texcoord)

        self.vertex_buffer = bgl.Buffer(bgl.GL_INT, 2)

        bgl.glGenBuffers(2, self.vertex_buffer)
        bgl.glBindBuffer(bgl.GL_ARRAY_BUFFER, self.vertex_buffer[0])
        bgl.glBufferData(bgl.GL_ARRAY_BUFFER, 32, position, bgl.GL_STATIC_DRAW)
        bgl.glVertexAttribPointer(position_location, 2, bgl.GL_FLOAT, bgl.GL_FALSE, 0, None)

        bgl.glBindBuffer(bgl.GL_ARRAY_BUFFER, self.vertex_buffer[1])
        bgl.glBufferData(bgl.GL_ARRAY_BUFFER, 32, texcoord, bgl.GL_STATIC_DRAW)
        bgl.glVertexAttribPointer(texturecoord_location, 2, bgl.GL_FLOAT, bgl.GL_FALSE, 0, None)

        bgl.glBindBuffer(bgl.GL_ARRAY_BUFFER, 0)
        bgl.glBindVertexArray(0)

    def __del__(self):
        log('CustomDrawData.__del__()')
        
        bgl.glDeleteBuffers(2, self.vertex_buffer)
        bgl.glDeleteVertexArrays(1, self.vertex_array)
        bgl.glBindTexture(bgl.GL_TEXTURE_2D, 0)
        bgl.glDeleteTextures(1, self.texture)

    def draw(self):
        log('CustomDrawData.draw()')
        
        bgl.glActiveTexture(bgl.GL_TEXTURE0)
        bgl.glBindTexture(bgl.GL_TEXTURE_2D, self.texture[0])
        bgl.glBindVertexArray(self.vertex_array[0])
        bgl.glDrawArrays(bgl.GL_TRIANGLE_FAN, 0, 4);
        bgl.glBindVertexArray(0)
        bgl.glBindTexture(bgl.GL_TEXTURE_2D, 0)


# RenderEngines also need to tell UI Panels that they are compatible with.
# We recommend to enable all panels marked as BLENDER_RENDER, and then
# exclude any panels that are replaced by custom panels registered by the
# render engine, or that are not supported.
def get_panels():
    exclude_panels = {
        'VIEWLAYER_PT_filter',
        'VIEWLAYER_PT_layer_passes',
    }

    panels = []
    for panel in bpy.types.Panel.__subclasses__():
        if hasattr(panel, 'COMPAT_ENGINES') and 'BLENDER_RENDER' in panel.COMPAT_ENGINES:
            if panel.__name__ not in exclude_panels:
                panels.append(panel)

    return panels

def register():
    # Register the RenderEngine
    bpy.utils.register_class(CustomRenderEngine)

    for panel in get_panels():
        panel.COMPAT_ENGINES.add('CUSTOM')

def unregister():
    bpy.utils.unregister_class(CustomRenderEngine)

    for panel in get_panels():
        if 'CUSTOM' in panel.COMPAT_ENGINES:
            panel.COMPAT_ENGINES.remove('CUSTOM')


if __name__ == "__main__":
    register()
